package cli

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// ReferenceMarkdown renders the CLI reference (docs/cli.md) from a command
// tree. The output is deterministic: commands appear in tree order, flags are
// sorted by name, defaults that depend on the machine are rendered
// symbolically, and there are no timestamps or absolute paths. Lines end with
// LF on every OS. It is hand-written instead of using cobra/doc, which would
// pull in additional dependencies.
func ReferenceMarkdown(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by `go run ./internal/tools/gendocs`. Do not edit by hand. -->\n\n")
	b.WriteString("# Brooom CLI reference\n\n")
	b.WriteString("Every command is a dry run unless `--apply` is given. Every command also accepts\n")
	b.WriteString("`-h, --help`. Run `brooom <command> --help` for the same text in your terminal.\n\n")
	b.WriteString("## Contents\n\n")
	b.WriteString("- [Global flags](#global-flags)\n")
	walkCommands(root, func(c *cobra.Command) {
		b.WriteString("- [`" + c.CommandPath() + "`](#" + anchor(c.CommandPath()) + ")\n")
	})
	b.WriteString("\n## Global flags\n\n")
	b.WriteString("These flags are accepted by every command.\n\n")
	writeFlagTable(&b, root.PersistentFlags())
	walkCommands(root, func(c *cobra.Command) { writeCommand(&b, c) })
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// walkCommands visits c and its visible descendants in tree order. Hidden
// commands (cobra's internal completion entry points) are not documented.
func walkCommands(c *cobra.Command, visit func(*cobra.Command)) {
	visit(c)
	for _, sub := range c.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		walkCommands(sub, visit)
	}
}

// anchor is the GitHub heading slug of a command path: lower case, spaces
// replaced by dashes.
func anchor(path string) string {
	return strings.ReplaceAll(strings.ToLower(path), " ", "-")
}

func writeCommand(b *strings.Builder, c *cobra.Command) {
	b.WriteString("\n## `" + c.CommandPath() + "`\n\n")
	b.WriteString(c.Short + "\n\n")
	b.WriteString("```text\n" + c.UseLine() + "\n```\n\n")
	if c.Long != "" {
		b.WriteString("```text\n" + trimLines(c.Long) + "\n```\n\n")
	}
	if c.Example != "" {
		b.WriteString("**Examples**\n\n```sh\n" + strings.TrimRight(dedent(c.Example), "\n") + "\n```\n\n")
	}
	if c.Parent() != nil {
		writeLocalFlags(b, c)
	}
	writeSubcommands(b, c)
}

// writeLocalFlags lists the flags a command declares itself; inherited global
// flags are documented once at the top of the page.
func writeLocalFlags(b *strings.Builder, c *cobra.Command) {
	local := pflag.NewFlagSet(c.Name(), pflag.ContinueOnError)
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Name != "help" {
			local.AddFlag(f)
		}
	})
	if !local.HasFlags() {
		return
	}
	b.WriteString("**Flags**\n\n")
	writeFlagTable(b, local)
	b.WriteString("\n")
}

func writeSubcommands(b *strings.Builder, c *cobra.Command) {
	var subs []*cobra.Command
	for _, sub := range c.Commands() {
		if !sub.Hidden && sub.Name() != "help" {
			subs = append(subs, sub)
		}
	}
	if len(subs) == 0 {
		return
	}
	b.WriteString("**Subcommands**\n\n")
	for _, sub := range subs {
		b.WriteString("- [`" + sub.CommandPath() + "`](#" + anchor(sub.CommandPath()) + "): " + sub.Short + "\n")
	}
	b.WriteString("\n")
}

// writeFlagTable renders flags (sorted by name by pflag) as a table.
func writeFlagTable(b *strings.Builder, fs *pflag.FlagSet) {
	b.WriteString("| Flag | Default | Description |\n| --- | --- | --- |\n")
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		b.WriteString("| " + name + " | " + flagDefault(f) + " | " + escapeCell(f.Usage) + " |\n")
	})
}

// flagDefault renders a default value for the table. Empty, false and empty
// list defaults are omitted (shown as a dash); values that contain the home
// directory or the working directory are rendered symbolically so the
// document is identical on every machine.
func flagDefault(f *pflag.Flag) string {
	switch f.DefValue {
	case "", "false", "[]", "0":
		return "-"
	}
	return "`" + symbolic(f.DefValue) + "`"
}

// symbolic replaces machine-specific absolute prefixes by placeholders.
func symbolic(v string) string {
	cwd, _ := os.Getwd()
	home, _ := os.UserHomeDir()
	return symbolicWith(v, cwd, home)
}

// symbolicWith is symbolic with the machine-specific prefixes passed in, so
// the replacement rules are testable on every OS.
func symbolicWith(v, cwd, home string) string {
	v = replacePath(v, cwd, "<cwd>")
	return replacePath(v, home, "~")
}

// replacePath replaces prefix by symbol only at path boundaries: the prefix
// must be followed by the end of the value or a separator, and must not be
// preceded by a path character. A plain substring replace would turn every
// slash into the symbol for a root prefix and match /home/u inside
// /home/user2. Empty and root prefixes are skipped for the same reason.
func replacePath(v, prefix, symbol string) string {
	if isRootPath(prefix) {
		return v
	}
	for _, p := range []string{filepath.ToSlash(prefix), prefix} {
		v = replaceAtBoundary(v, strings.TrimRight(p, `/\`), symbol)
	}
	return v
}

// isRootPath reports whether p is empty or consists only of separators or is a
// volume root such as C:\.
func isRootPath(p string) bool {
	rest := strings.Trim(p, `/\`)
	// A drive letter is recognised by hand so the rule also holds when the
	// document is generated on a unix host with a Windows-style value.
	if len(rest) == 2 && rest[1] == ':' {
		return true
	}
	return rest == "" || filepath.Dir(p) == p
}

// replaceAtBoundary replaces every occurrence of prefix that starts the value
// or follows a non-path character (a list separator, a quote, a space) and
// ends the value or precedes a separator.
func replaceAtBoundary(v, prefix, symbol string) string {
	var b strings.Builder
	for {
		i := strings.Index(v, prefix)
		if i < 0 {
			b.WriteString(v)
			return b.String()
		}
		end := i + len(prefix)
		startOK := i == 0 || !isPathChar(v[i-1])
		endOK := end == len(v) || v[end] == '/' || v[end] == '\\'
		if startOK && endOK {
			b.WriteString(v[:i] + symbol)
		} else {
			b.WriteString(v[:end])
		}
		v = v[end:]
	}
}

// isPathChar reports whether c can be part of a path element, which is what
// makes a match in the middle of a longer path.
func isPathChar(c byte) bool {
	return c != ' ' && c != ',' && c != ':' && c != ';' && c != '"' && c != '\'' && c != '[' && c != '='
}

// escapeCell keeps flag descriptions from breaking the table.
func escapeCell(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ")
}

// trimLines strips trailing whitespace of every line and of the text, so
// editor settings in help strings cannot make the document unstable.
func trimLines(s string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		lines[i] = strings.TrimRight(l, " \t\r")
	}
	return strings.TrimRight(strings.Join(lines, "\n"), "\n")
}

// dedent removes the common leading indentation of an example block; the
// cobra convention is to indent examples by two spaces for the help output.
func dedent(s string) string {
	lines := strings.Split(s, "\n")
	indent := -1
	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			continue
		}
		n := len(l) - len(strings.TrimLeft(l, " "))
		if indent < 0 || n < indent {
			indent = n
		}
	}
	for i, l := range lines {
		if len(l) >= indent && indent > 0 {
			lines[i] = strings.TrimRight(l[indent:], " ")
		} else {
			lines[i] = strings.TrimRight(l, " ")
		}
	}
	return strings.Join(lines, "\n")
}
